@startuml
skinparam classAttributeIconSize 0
skinparam monochrome true
skinparam shadowing false

'=========================
' CLASES PRINCIPALES
'=========================
class Manager {
  - host : string 
  - community : string
  - version : string           ' v1 | v2c
  - trapReceiver : string 
  + get(oid : String) : any
  + set(oid : String, val : any) : int
  + receiveNotification() : void
}

class Agent {
  - mib : Mib
  - samplerPeriod : integer     ' s
  - trapTarget : string
  + start() : void
  + stop() : void
  + restart() : void
  + onGet(oid : String) : any
  + onSet(oid : String, val : any) : int
  + updateCpu() : void
  + checkThreshold() : void
  + sendNotification() : void   ' trap v1 / notification v2c
  + sendEmail() : void
}

class Mib {
  - oidTable : Map
  - index : List<string>
  - pathJSON : string
  + manager : DisplayString        ' RW
  + managerEmail : DisplayString   ' RW
  + cpuUsage : Integer32           ' RO, 0..100 (%)
  + cpuThreshold : Integer32       ' RW, 0..100 (%), DEFVAL 80
  + dateAndTime : DateAndTime      ' RO (SNMPv2-TC)
  + get(oid : String) : any
  + getNext(oid : String) : (string, any)
  + set(oid : String, val : any) : void
  + load() : void
  + save() : void
  + setCpuUsageInternal(pct : int) : void
}

'=========================
' RELACIONES
'=========================
Manager --> Agent : GET / SET
Agent --> Manager : TRAP v1 / INFORM | NOTIFICATION v2c
Agent *-- Mib : composición
Agent ..> Mib : lee/escribe

'=========================
' NOTIFICACIÓN
'=========================
note right of Agent
Notification: cpuOverThresholdNotification
varBinds: cpuUsage, cpuThreshold, managerEmail, dateAndTime
Condición: cpuUsage > cpuThreshold
end note

@enduml
